version: "3.7"
services:
    automedsys-backoffice_app:
        build:
            context: .
        restart: unless-stopped
        volumes:
            - ./:/var/www/app
            - /var/www/app/vendor
        ports:
            - "${PORT}:80"
