version: '3'
services:
  automedbko-web-ci4-new:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
      args:
        uid: ${UID}
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./apache_log:/var/log/apache2

    extra_hosts:
      - "dev-api.automedsys.net:10.10.10.3"
      - "stgmw.automedsys.net:10.10.10.3"
      - "smtp.gmail.com:173.194.206.108"
    ports:
      - 8235:80
volumes:
  src: