version: "3.7"
services:
    automedsys-backoffice_app:
        build:
            context: .
        restart: unless-stopped
        volumes:
            - ./:/var/www/app
            - /var/www/app/vendor
        extra_hosts:
            - "dev-api.automedsys.net:10.10.10.3"
        ports:
            - "${PORT}:80"
